[2025-01-02T13:29:57.029+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T13:29:57.118+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_finance_data_pipeline.pyspark_task manual__2025-01-02T13:29:49.745507+00:00 [queued]>
[2025-01-02T13:29:57.151+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_finance_data_pipeline.pyspark_task manual__2025-01-02T13:29:49.745507+00:00 [queued]>
[2025-01-02T13:29:57.151+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2025-01-02T13:29:57.233+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): pyspark_task> on 2025-01-02 13:29:49.745507+00:00
[2025-01-02T13:29:57.319+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'gold_finance_data_pipeline', 'pyspark_task', 'manual__2025-01-02T13:29:49.745507+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/Gold_finance_etl_dags.py', '--cfg-path', '/tmp/tmpp8ldgw2_']
[2025-01-02T13:29:57.303+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1978) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-02T13:29:57.336+0000] {standard_task_runner.py:72} INFO - Started process 1980 to run task
[2025-01-02T13:29:57.324+0000] {standard_task_runner.py:105} INFO - Job 302: Subtask pyspark_task
[2025-01-02T13:29:57.762+0000] {task_command.py:467} INFO - Running <TaskInstance: gold_finance_data_pipeline.pyspark_task manual__2025-01-02T13:29:49.745507+00:00 [running]> on host 77bcd09e75b5
[2025-01-02T13:29:57.952+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_finance_data_pipeline' AIRFLOW_CTX_TASK_ID='pyspark_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T13:29:49.745507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-02T13:29:49.745507+00:00'
[2025-01-02T13:29:57.955+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T13:30:05.993+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2025-01-02T13:30:05.997+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-02T13:30:05.997+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2025-01-02T13:30:06.002+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-01-02T13:30:06.003+0000] {logging_mixin.py:190} INFO - An error occurred: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext
[2025-01-02T13:30:06.004+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-02T13:30:06.024+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T13:30:06.025+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=gold_finance_data_pipeline, task_id=pyspark_task, run_id=manual__2025-01-02T13:29:49.745507+00:00, execution_date=20250102T132949, start_date=20250102T132957, end_date=20250102T133006
[2025-01-02T13:30:06.074+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-02T13:30:06.108+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-02T13:30:06.113+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
