[2024-12-24T18:59:24.784+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-24T18:59:24.807+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Gold_finance_ETL_pipeline.api_test manual__2024-12-24T18:59:02.784789+00:00 [queued]>
[2024-12-24T18:59:24.817+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Gold_finance_ETL_pipeline.api_test manual__2024-12-24T18:59:02.784789+00:00 [queued]>
[2024-12-24T18:59:24.818+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-24T18:59:24.836+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): api_test> on 2024-12-24 18:59:02.784789+00:00
[2024-12-24T18:59:24.843+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=698) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-24T18:59:24.848+0000] {standard_task_runner.py:72} INFO - Started process 700 to run task
[2024-12-24T18:59:24.846+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Gold_finance_ETL_pipeline', 'api_test', 'manual__2024-12-24T18:59:02.784789+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/finance_etl_dags.py', '--cfg-path', '/tmp/tmpi2lm4tem']
[2024-12-24T18:59:24.849+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask api_test
[2024-12-24T18:59:24.913+0000] {task_command.py:467} INFO - Running <TaskInstance: Gold_finance_ETL_pipeline.api_test manual__2024-12-24T18:59:02.784789+00:00 [running]> on host 3dbe838a1c54
[2024-12-24T18:59:25.029+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Gold_finance_ETL_pipeline' AIRFLOW_CTX_TASK_ID='api_test' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T18:59:02.784789+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T18:59:02.784789+00:00'
[2024-12-24T18:59:25.030+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-24T18:59:25.436+0000] {logging_mixin.py:190} INFO - API Test failed for IBM: "Expected key 'Time Series (Daily)' not found in response."
[2024-12-24T18:59:25.437+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/extract_test.py", line 31, in validate_api_response
    raise error
  File "/opt/airflow/dags/modules/extract_test.py", line 25, in validate_api_response
    data = fetch_api_data(symbol, api_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/extract_test.py", line 18, in fetch_api_data
    raise KeyError(f"Expected key 'Time Series (Daily)' not found in response.")
KeyError: "Expected key 'Time Series (Daily)' not found in response."
[2024-12-24T18:59:25.454+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Gold_finance_ETL_pipeline, task_id=api_test, run_id=manual__2024-12-24T18:59:02.784789+00:00, execution_date=20241224T185902, start_date=20241224T185924, end_date=20241224T185925
[2024-12-24T18:59:25.481+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-24T18:59:25.481+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task api_test ("Expected key 'Time Series (Daily)' not found in response."; 700)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/extract_test.py", line 31, in validate_api_response
    raise error
  File "/opt/airflow/dags/modules/extract_test.py", line 25, in validate_api_response
    data = fetch_api_data(symbol, api_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/extract_test.py", line 18, in fetch_api_data
    raise KeyError(f"Expected key 'Time Series (Daily)' not found in response.")
KeyError: "Expected key 'Time Series (Daily)' not found in response."
[2024-12-24T18:59:25.505+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-24T18:59:25.541+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-24T18:59:25.547+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
